### ISSUE TITLE
关于第二题，小老弟的答案

### ISSUE THREAD

**Issue by HYSWZW** [bowu678/php_bugs#12]
同时提交GET和POST：
GET提交：number=0e00
POST提交：number[]=0x01
![Image](https://user-images.githubusercontent.com/18552371/91632503-cba3a880-ea13-11ea-9139-7ecd7aabad46.png)

**Comment by zzzskd** [comment]
也可以直接 index.php?number=0e00%20

**Comment by HYSWZW** [comment]
关咯
